from django.conf.urls import url
from django.urls import path
from .views import (
    Customer,
    CustomerDetail,
    Trade,
    TradeDetail,
    Product,
    ProductDetail,
    History,
    HistoryDetail,
    Calendar,
    CalendarDetail,
    Category,
    CategoryDetail,
    Test,
    HistoryAllDelete,
    ReceivableView,
    MyasView,
    EngineerDetail,
    Engineer,
    UserIdCheck,
    DashBoardView,
    ReleaseView,
    ReleaseDetailView,
    RecordView,
    RecordDetailView,
    AttendanceView,
    VacationView,
    VacationDetailView,
    ExcelView,
    AccountingCalcView,
    ExportDataToExcelView,
    ReleaseLogView,
)


urlpatterns = [
    url(r"^customer/(?P<customer_id>\d+)/$", CustomerDetail.as_view()),
    url(r"^customers", Customer.as_view()),
    url(r"^product/(?P<product_id>\d+)/$", ProductDetail.as_view()),
    url(r"^products", Product.as_view()),
    url(r"^trade/(?P<trade_id>\d+)/$", TradeDetail.as_view()),
    url(r"^trades", Trade.as_view()),
    url(r"^history/(?P<history_id>\d+)/$", HistoryDetail.as_view()),
    url(r"^histories", History.as_view()),
    url(r"^calendar/(?P<calendar_id>\d+)/$", CalendarDetail.as_view()),
    url(r"^calendars", Calendar.as_view()),
    url(r"^engineers", Engineer.as_view()),
    url(r"^engineer/(?P<engineer_id>\d+)/$", EngineerDetail.as_view()),
    url(r"^userIdCheck/", UserIdCheck.as_view()),
    url(r"^category/(?P<category_id>\d+)/$", CategoryDetail.as_view()),
    url(r"^categories", Category.as_view()),
    url(r"^hisall/(?P<trade_id>\d+)/$", HistoryAllDelete.as_view()),
    url(r"^myas", MyasView.as_view()),
    url(r"^test", Test.as_view()),
    url(r"^receivable", ReceivableView.as_view()),
    url(r"^dashboard", DashBoardView.as_view()),
    url(r"^release/(?P<release_id>\d+)", ReleaseDetailView.as_view()),
    url(r"^release/log", ReleaseLogView.as_view()),
    url(r"^release", ReleaseView.as_view()),
    url(r"record/(?P<record_id>\d+)", RecordDetailView.as_view()),
    url(r"record", RecordView.as_view()),
    url(r"attendance", AttendanceView.as_view()),
    url(r"vacation/(?P<vacation_id>\d+)", VacationDetailView.as_view()),
    url(r"vacation", VacationView.as_view()),
    path("excel", ExcelView.as_view()),
    url(r"accountingCalc", AccountingCalcView.as_view()),
    url(r"export/excel/", ExportDataToExcelView.as_view()),
]
