# Generated by Django 3.1.12 on 2026-01-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_productpackage_productpackageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, '입고대기'), (1, '입고완료'), (2, '바로판매'), (3, '취소')], default=0)),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('register_name', models.CharField(blank=True, max_length=50, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_stocks', related_query_name='pending_stock', to='model.history')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_stocks', related_query_name='pending_stock', to='model.product')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_stocks', related_query_name='pending_stock', to='model.trade')),
            ],
        ),
    ]
