# Generated by Django 3.1.12 on 2026-01-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20260108_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseLogPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.IntegerField(unique=True)),
                ('can_view_register', models.BooleanField(default=False)),
                ('can_view_sale', models.BooleanField(default=False)),
                ('can_view_delete', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
