# Generated by Django 3.2.11 on 2026-01-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_pendingstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaselogpermission',
            name='can_export_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='releaselogpermission',
            name='can_export_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='releaselogpermission',
            name='can_export_trade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
