# Generated by Django 3.2.11 on 2026-01-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20260122_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaselogpermission',
            name='can_export_accounting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='releaselogpermission',
            name='can_export_receivable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='releaselogpermission',
            name='can_export_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='releaselogpermission',
            name='can_export_release_log',
            field=models.BooleanField(default=False),
        ),
    ]
