# Generated by Django 3.2.11 on 2026-01-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20260122_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_leader_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='category',
            field=models.IntegerField(choices=[(0, '경영관리'), (1, '기술지원'), (2, '대표이사'), (3, '관리자'), (4, '연구개발'), (5, '전략기획'), (6, '생산품질관리'), (7, '영업홍보')]),
        ),
    ]
