# Generated by Django 3.2.11 on 2026-01-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20260129_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='is_leader_approved',
        ),
    ]
