# Generated by Django 3.2.11 on 2026-01-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsInternalProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('register_name', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_processes', related_query_name='internal_process', to='model.engineer')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_processes', related_query_name='internal_process', to='model.trade')),
            ],
        ),
    ]
