# Generated by Django 3.2.11 on 2026-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_asinternalprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='category_3',
            field=models.IntegerField(blank=True, choices=[(0, 'INSIDE'), (1, 'OUTSIDE'), (2, 'CONSTRUCTION'), (3, 'INTERNAL')], null=True),
        ),
    ]
