# Generated by Django 3.2.11 on 2026-02-03 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0012_alter_trade_category_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='engineer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendars', related_query_name='calendar', to='model.engineer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', related_query_name='record', to=settings.AUTH_USER_MODEL),
        ),
    ]
