# Generated by Django 3.2.11 on 2026-02-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_auto_20260203_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
