# Generated by Django 3.2.11 on 2026-02-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_calendar_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='bg_color',
            field=models.CharField(blank=True, default='#00a9ff', max_length=20, null=True),
        ),
    ]
