# Generated by Django 3.2.11 on 2026-02-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_calendar_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='model.trade'),
        ),
    ]
