# Generated by Django 3.2.11 on 2026-02-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_calendar_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_receivable_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='receivable',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
