# Generated by Django 3.2.11 on 2026-04-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_auto_20260227_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_trades', to='model.Engineer'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='category_1',
            field=models.IntegerField(choices=[(0, 'AS'), (1, 'COLLECTION'), (2, 'PAYMENT'), (3, 'SELL'), (4, 'PURCHASE'), (5, 'INCOME'), (6, 'OUTCOME'), (7, 'DELIVER'), (8, 'MEMO'), (9, 'CONSTRUCTION')], null=True),
        ),
    ]
