# Generated by Django 3.2.11 on 2026-04-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_auto_20260401_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingstock',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
