# Generated by Django 3.2.11 on 2026-05-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0020_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
