export default [
  {
    id: 'Ryu',
    name: '류승영',
    color: '#FFFFFF',
    bgColor: '#FF5583',
    dragBgColor: '#FF5583',
    borderColor: '#FF5583',
  },
  {
    id: 'Kim',
    name: '김영기',
    color: '#FFFFFF',
    bgColor: '#FFBB3B',
    dragBgColor: '#FFBB3B',
    borderColor: '#FFBB3B',
  },
  {
    id: 'Seo',
    name: '서우종',
    color: '#FFFFFF',
    bgColor: '#03BD9E',
    dragBgColor: '#03BD9E',
    borderColor: '#03BD9E',
  },
  {
    id: 'Choi',
    name: '최규민',
    color: '#FFFFFF',
    bgColor: '#aadbee',
    dragBgColor: '#aadbee',
    borderColor: '#aadbee',
  },
  {
    id: 'Koh',
    name: '고영훈',
    color: '#FFFFFF',
    bgColor: '#4169E1',
    dragBgColor: '#4169E1',
    borderColor: '#4169E1',
  },
  {
    id: 'tae',
    name: '김태우',
    color: '#FFFFFF',
    bgColor: '#FF4500',
    dragBgColor: '#FF4500',
    borderColor: '#FF4500',
  },
  {
    id: 'lim',
    name: '임환규',
    color: '#FFFFFF',
    bgColor: '#bdb76b',
    dragBgColor: '#bdb76b',
    borderColor: '#bdb76b',
  },
];
