# Generated by Django 4.2 on 2025-09-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0002_devicenameconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
