# Generated by Django 3.2 on 2025-12-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0003_alter_profile_options_profile_order'),
        ('matrix_web', '0006_videowall'),
    ]

    operations = [
    ]
