# Generated by Django 3.2 on 2025-12-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0007_merge_20251212_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicenameconfig',
            options={'verbose_name': '디바이스 이름 설정', 'verbose_name_plural': '디바이스 이름 설정들'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '프로필', 'verbose_name_plural': '프로필들'},
        ),
        migrations.AlterField(
            model_name='devicenameconfig',
            name='device_name',
            field=models.CharField(default='', help_text='표시할 장비 이름', max_length=200),
        ),
        migrations.AlterModelTable(
            name='devicenameconfig',
            table='matrix_web_devicenameconfig',
        ),
    ]
